### ISSUE TITLE
Error: Could not open file lib.yaoui/fonts/OpenSans-Light.ttf. Does not exist.

### ISSUE THREAD

**Issue by unek** [adonaac/yaoui#2]
i mean it's pretty obvious what happens here

**Comment by a327ex** [comment]
The OpenSans-Light font is there though. How do the other fonts load but not that one?

**Comment by unek** [comment]
I mean there's no such folder as lib.yaoui, there's lib/yaoui, but since you use `...` for the path that's what happens

**Comment by a327ex** [comment]
I don't understand. Is yaoui in the lib folder? Also, why does OpenSans-Light not load but the other fonts load, even though they're in the same folder?

**Comment by unek** [comment]
`local yaoui_path = (...):sub(1, -12)` - this gives "lib.yaoui" if `yaoui` is in `lib` directory.

so when you're doing this:

``` lua
YaouiTheme.font_awesome_path = yaoui_path .. '/fonts/fontawesome-webfont.ttf'
YaouiTheme.open_sans_regular = yaoui_path .. '/fonts/OpenSans-Regular.ttf'
YaouiTheme.open_sans_light = yaoui_path .. '/fonts/OpenSans-Light.ttf'
YaouiTheme.open_sans_bold = yaoui_path .. '/fonts/OpenSans-Bold.ttf'
YaouiTheme.open_sans_semibold = yaoui_path .. '/fonts/OpenSans-Semibold.ttf'
```

you're using an incorrect path since there is no `lib.yaoui` directory. you need to replace the . with /.

and it crashes for opensans-light because this is the first loaded font.

**Comment by unek** [comment]
now [this](https://github.com/adonaac/yaoui/blob/b6110932c072d5e2042fc3b811b373ad407fd026/yaoui/YaouiTheme.lua#L45) will be wrong, won't it?

**Comment by a327ex** [comment]
I don't know, I don't have a Linux system to test. Does it work or does it bug out?

**Comment by unek** [comment]
I don't have a Linux system either. But you should change it to use periods instead of slashes.

**Comment by a327ex** [comment]
When someone complains :cyclone:
